; KiNGO keeps the native NSIS flow but uses shorter, modern Chinese copy so
; narrow installer pages do not split words or create crowded paragraphs.
!pragma warning disable 6030
LangString MUI_TEXT_WELCOME_INFO_TITLE ${LANG_SIMPCHINESE} "欢迎安装 KiNGO"
LangString MUI_TEXT_WELCOME_INFO_TEXT ${LANG_SIMPCHINESE} "KiNGO 将安装到你的电脑。$\r$\n$\r$\n建议先关闭正在运行的 KiNGO 和相关代理核心。$\r$\n$\r$\n点击“下一步”继续。"
LangString MUI_TEXT_INSTALLING_SUBTITLE ${LANG_SIMPCHINESE} "正在写入应用文件和内置核心，请稍候。"
LangString MUI_TEXT_FINISH_SUBTITLE ${LANG_SIMPCHINESE} "KiNGO 已成功安装。"
LangString MUI_TEXT_FINISH_INFO_TITLE ${LANG_SIMPCHINESE} "KiNGO 安装完成"
LangString MUI_TEXT_FINISH_INFO_TEXT ${LANG_SIMPCHINESE} "KiNGO 已成功安装到本机。$\r$\n$\r$\n点击“完成”退出安装程序。"
LangString MUI_TEXT_FINISH_RUN ${LANG_SIMPCHINESE} "立即运行 KiNGO(&R)"
LangString MUI_TEXT_ABORTWARNING ${LANG_SIMPCHINESE} "确定要退出 KiNGO 安装程序吗？"
!pragma warning enable 6030

LangString addOrReinstall ${LANG_SIMPCHINESE} "添加或重新安装组件"
LangString alreadyInstalled ${LANG_SIMPCHINESE} "已安装 KiNGO"
LangString alreadyInstalledLong ${LANG_SIMPCHINESE} "${PRODUCTNAME} ${VERSION} 已安装。请选择操作并点击“下一步”。"
LangString appRunning ${LANG_SIMPCHINESE} "{{product_name}} 正在运行，请先关闭程序后重试。"
LangString appRunningOkKill ${LANG_SIMPCHINESE} "{{product_name}} 正在运行！$\n点击“确定”关闭程序。"
LangString chooseMaintenanceOption ${LANG_SIMPCHINESE} "请选择维护操作。"
LangString choowHowToInstall ${LANG_SIMPCHINESE} "请选择 ${PRODUCTNAME} 的安装方式。"
LangString createDesktop ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString dontUninstall ${LANG_SIMPCHINESE} "保留当前版本"
LangString dontUninstallDowngrade ${LANG_SIMPCHINESE} "不卸载（此安装包不允许直接降级）"
LangString failedToKillApp ${LANG_SIMPCHINESE} "无法关闭 {{product_name}}，请手动关闭后重试。"
LangString installingWebview2 ${LANG_SIMPCHINESE} "正在安装 WebView2…"
LangString newerVersionInstalled ${LANG_SIMPCHINESE} "已安装更高版本的 ${PRODUCTNAME}。如需降级，请先卸载当前版本。"
LangString older ${LANG_SIMPCHINESE} "较旧"
LangString olderOrUnknownVersionInstalled ${LANG_SIMPCHINESE} "已安装 ${PRODUCTNAME} $R4。建议先卸载，再继续安装。"
LangString silentDowngrades ${LANG_SIMPCHINESE} "此安装包不允许静默降级，请使用图形安装界面。$\n"
LangString unableToUninstall ${LANG_SIMPCHINESE} "无法卸载当前版本！"
LangString uninstallApp ${LANG_SIMPCHINESE} "卸载 ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_SIMPCHINESE} "安装前卸载当前版本"
LangString unknown ${LANG_SIMPCHINESE} "未知"
LangString webview2AbortError ${LANG_SIMPCHINESE} "WebView2 安装失败，KiNGO 无法在缺少 WebView2 时运行。请重新启动安装程序。"
LangString webview2DownloadError ${LANG_SIMPCHINESE} "WebView2 下载失败：$0"
LangString webview2DownloadSuccess ${LANG_SIMPCHINESE} "WebView2 安装程序下载完成"
LangString webview2Downloading ${LANG_SIMPCHINESE} "正在下载 WebView2 安装程序…"
LangString webview2InstallError ${LANG_SIMPCHINESE} "WebView2 安装失败，退出代码：$1"
LangString webview2InstallSuccess ${LANG_SIMPCHINESE} "WebView2 安装完成"
LangString deleteAppData ${LANG_SIMPCHINESE} "删除 KiNGO 的应用数据"
